export const icon = [{
    namespace:'metaweather',
    name:'sn',
    url:'./assets/sn.svg'
},
{
    namespace:'metaweather',
    name:'sl',
    url:'./assets/sl.svg'
},
{
    namespace:'metaweather',
    name:'h',
    url:'./assets/h.svg'
},
{
    namespace:'metaweather',
    name:'t',
    url:'./assets/t.svg'
},{
    namespace:'metaweather',
    name:'hr',
    url:'./assets/hr.svg'
},{
    namespace:'metaweather',
    name:'lr',
    url:'./assets/lr.svg'
},{
    namespace:'metaweather',
    name:'s',
    url:'./assets/s.svg'
},{
    namespace:'metaweather',
    name:'hc',
    url:'./assets/hc.svg'
},{
    namespace:'metaweather',
    name:'lc',
    url:'./assets/lc.svg'
},{
    namespace:'metaweather',
    name:'c',
    url:'./assets/c.svg'
}];
