export const icon = [{
    namespace:'metaweather',
    name:'sn',
    url:'./assets/sn.svg'
},
{
    namespace:'metaweather',
    name:'sl',
    url:'https://www.metaweather.com/static/img/weather/sl.svg'
},
{
    namespace:'metaweather',
    name:'h',
    url:'https://www.metaweather.com/static/img/weather/h.svg'
},
{
    namespace:'metaweather',
    name:'t',
    url:'https://www.metaweather.com/static/img/weather/t.svg'
},{
    namespace:'metaweather',
    name:'hr',
    url:'https://www.metaweather.com/static/img/weather/hr.svg'
},{
    namespace:'metaweather',
    name:'lr',
    url:'https://www.metaweather.com/static/img/weather/lr.svg'
},{
    namespace:'metaweather',
    name:'s',
    url:'./assets/s.svg'
},{
    namespace:'metaweather',
    name:'hc',
    url:'https://www.metaweather.com/static/img/weather/hc.svg'
},{
    namespace:'metaweather',
    name:'lc',
    url:'https://www.metaweather.com/static/img/weather/lc.svg'
},{
    namespace:'metaweather',
    name:'c',
    url:'https://www.metaweather.com/static/img/weather/c.svg'
}];
